PREFIX analysis:	<http://imce.jpl.nasa.gov/foundation/analysis#>
PREFIX constraint:	<http://opencaesar.io/firesat-telecom/telecom-supplier/vocabulary/constraint#>
PREFIX rdfs:		<http://www.w3.org/2000/01/rdf-schema#>
PREFIX odd:	<http://opencaesar.io/template/vocabulary/ADSdomain#>
PREFIX ec:	<http://opencaesar.io/template/vocabulary/EnverionmentalCondition/EnverionmentalCondition#>

SELECT DISTINCT* #?odd ?oe ?iri ?cloudiness

WHERE {
#  <http://opencaesar.io/template/description/scene/scene02#odd-2> a odd:JASPARODD;
  VALUES ?odd {<http://opencaesar.io/template/description/scene/scene01#odd-01>}
#  ?odd a odd:JASPARODD;
  VALUES ?oe { odd:EnverionmentalCondition }
  VALUES ?relation { odd:isECOf}
  ?iri a ?oe;
     ?relation ?odd;
     ec:cloudiness ?cloudiness;
     ec:cloudiness ?cloudiness;
     ec:dust_storm ?dust_storm;
  	 ec:fog_density ?fog_density;
     ec:fog_distance ?fog_distance;
     ec:fog_falloff ?fog_falloff;
     ec:mie_scattering_scale ?mie_scattering_scale;
     ec:precipitation ?precipitation;
     ec:precipitation_deposits ?precipitation_deposits;
     ec:rayleigh_scattering_scale ?rayleigh_scattering_scale;
     ec:sun_altitude_angle ?sun_altitude_angle;
     ec:sun_azimuth_angle ?sun_azimuth_angle;
     ec:wetness ?wetness;
     ec:wind_intensity ?wind_intensity.

}ORDER BY ?odd ?oe
