PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX base:        <http://imce.jpl.nasa.gov/foundation/base#>
PREFIX mission:        <http://imce.jpl.nasa.gov/foundation/mission#>

SELECT DISTINCT ?iri ?id ?name ?type
WHERE {

  VALUES ?componentType { mission:Objective }
  ?iri a ?componentType ;
    base:hasIdentifier ?id ;
    base:hasCanonicalName ?name .

BIND(
    IF(CONTAINS(STR(?iri), "missions#"), "missions",
      IF(CONTAINS(STR(?iri), "objectives#"), "Subsystem", "")
    ) AS ?type
  )


 }
ORDER BY ?id